In [42]:
import pandas as pd

**1. โหลดไฟล์ชื่อ olympic_cleaned.csv ขึ้นมาใน DataFrame ชื่อ medals**

In [43]:
medals = pd.read_csv('olympics_cleaned.csv')

**2. แสดงจนวนแถวและจนวนคอลมนของ medals**

In [44]:
medals # shape = 146, 10

,Country,Code,SummerGame,SummerGold,SummerSilver,SummerBronze,WinterGame,WinterGold,WinterSilver,WinterBronze
0,Afghanistan,AFG,13,0,0,2,0,0,0,0
1,Algeria,ALG,12,5,2,8,3,0,0,0
2,Argentina,ARG,23,18,24,28,18,0,0,0
3,Armenia,ARM,5,1,2,9,6,0,0,0
4,Australasia,ANZ,2,3,4,5,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
141,Yugoslavia,YUG,16,26,29,28,14,0,3,1
142,Independent Olympic Participants,IOP,1,0,1,2,0,0,0,0
143,Zambia,ZAM,12,0,1,1,0,0,0,0
144,Zimbabwe,ZIM,12,3,4,1,1,0,0,0
145,Mixed team,ZZX,3,8,5,4,0,0,0,0

**3. ตรวจสอบวารหัสประเทศ (Code) ไมมีซํ้ากันดวย attribute is_unique**

In [45]:
medals['Code'].nunique() == medals.shape[0]

True

**4. ตั้งรหัสประเทศใหเป็น index**

In [46]:
medals.set_index('Code')

,Country,SummerGame,SummerGold,SummerSilver,SummerBronze,WinterGame,WinterGold,WinterSilver,WinterBronze
Code,,,,,,,,,
AFG,Afghanistan,13,0,0,2,0,0,0,0
ALG,Algeria,12,5,2,8,3,0,0,0
ARG,Argentina,23,18,24,28,18,0,0,0
ARM,Armenia,5,1,2,9,6,0,0,0
ANZ,Australasia,2,3,4,5,0,0,0,0
...,...,...,...,...,...,...,...,...,...
YUG,Yugoslavia,16,26,29,28,14,0,3,1
IOP,Independent Olympic Participants,1,0,1,2,0,0,0,0
ZAM,Zambia,12,0,1,1,0,0,0,0
ZIM,Zimbabwe,12,3,4,1,1,0,0,0
ZZX,Mixed team,3,8,5,4,0,0,0,0

**5. แสดงคอลัมน์เหรียญทองโอลิมปิคฤดูร้อน (SummerGold)**

In [47]:
medals[['Code', 'SummerGold']]

    Code  SummerGold
0    AFG           0
1    ALG           5
2    ARG          18
3    ARM           1
4    ANZ           3
..   ...         ...
141  YUG          26
142  IOP           0
143  ZAM           0
144  ZIM           3
145  ZZX           8

[146 rows x 2 columns]

**6. แสดงข้อมูลของประเทศสหรัฐอเมริกา (USA)**

In [48]:
medals[medals['Code'] == 'USA']

,Country,Code,SummerGame,SummerGold,SummerSilver,SummerBronze,WinterGame,WinterGold,WinterSilver,WinterBronze
135,United States,USA,26,976,757,666,22,96,102,84

**7. แสดงเฉพาะข้อมลของโอลิมปิคฤดูร้อนของทุกประเทศ (คอลัมน์ที่ขึ้นต้นด้วยคำว่า Summer)**

In [72]:
medals.iloc[:, 1:6]

    Code  SummerGame  SummerGold  SummerSilver  SummerBronze
0    AFG          13           0             0             2
1    ALG          12           5             2             8
2    ARG          23          18            24            28
3    ARM           5           1             2             9
4    ANZ           2           3             4             5
..   ...         ...         ...           ...           ...
141  YUG          16          26            29            28
142  IOP           1           0             1             2
143  ZAM          12           0             1             1
144  ZIM          12           3             4             1
145  ZZX           3           8             5             4

[146 rows x 5 columns]

**8. แสดงข้อมูลเหรียญทองของโอลิมปิกฤดูร้อนและฤดูหนาวของประเทศไทย (THA) สิงคโปร์ (SIN) และมาเล
เซีย (MAS) แสดงชื่อประเทศด้วย**

In [53]:
medals.loc[medals['Code'].isin(['THA', 'SIN', 'MAS'])][['Country','SummerGold', 'WinterGold']]

       Country  SummerGold  WinterGold
79    Malaysia           0           0
112  Singapore           0           0
126   Thailand           7           0

**9. แสดงข้อมลเหรียญเงินและเหรียญทองแดงของโอลิมปคฤดูร้อนของประเทศฝรงเศส (FRA) และสเปน (ESP)
แสดงชื่อประเทศด้วย**

In [74]:
medals.loc[medals['Code'].isin(['FRA', 'ESP'])][['Country', 'SummerSilver', 'WinterSilver', 'SummerSilver', 'WinterBronze']]

    Country  SummerSilver  WinterSilver  SummerSilver  WinterBronze
41   France           223            31           223            47
116   Spain            59             0            59             1

**10. แสดงประเทศที่เข้าร่วมโอลิมปิคฤดูร้อนมากกว่า 24 ครั้ง**

In [84]:
medals.query('SummerGame > 24').iloc[:, :6]

           Country Code  SummerGame  SummerGold  SummerSilver  SummerBronze
5        Australia  AUS          25         139           152           177
6          Austria  AUT          26          18            33            35
12         Belgium  BEL          25          37            52            53
21          Canada  CAN          25          59            99           121
32         Denmark  DEN          26          43            68            68
41          France  FRA          27         202           223           246
49   Great Britain  GBR          27         236           272           272
50          Greece  GRE          27          30            42            39
56         Hungary  HUN          25         167           144           165
64           Italy  ITA          26         198           166           185
88     Netherlands  NED          25          77            85           104
120         Sweden  SWE          26         143           164           176
121    Switzerland  SUI          27          47            73            65
135  United States  USA          26         976           757           666

**11. แสดงประเทศที่ได้เหรียญทองของโอลิมปิคฤดูร้อนมากกว่า 200 เหรียญ**

In [86]:
medals.query('SummerGold > 200')

,Country,Code,SummerGame,SummerGold,SummerSilver,SummerBronze,WinterGame,WinterGold,WinterSilver,WinterBronze
23,China,CHN,9,201,146,126,10,12,22,19
41,France,FRA,27,202,223,246,22,31,31,47
49,Great Britain,GBR,27,236,272,272,22,10,4,12
106,Soviet Union,URS,9,395,319,296,9,78,57,59
135,United States,USA,26,976,757,666,22,96,102,84