## ปริยวิศว์ เตชะกฤตเมธีธำรง 6510450593

In [575]:
import pandas as pd

## 1

In [576]:
medals = pd.read_csv('olympics_cleaned.csv')
medals.head()

,Country,Code,SummerGame,SummerGold,SummerSilver,SummerBronze,WinterGame,WinterGold,WinterSilver,WinterBronze
0,Afghanistan,AFG,13,0,0,2,0,0,0,0
1,Algeria,ALG,12,5,2,8,3,0,0,0
2,Argentina,ARG,23,18,24,28,18,0,0,0
3,Armenia,ARM,5,1,2,9,6,0,0,0
4,Australasia,ANZ,2,3,4,5,0,0,0,0

## 2

In [577]:
drinks = pd.read_csv('drinks.csv')
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF

## 3

In [578]:
drinks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193 entries, 0 to 192
Data columns (total 6 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   country                       193 non-null    object
 1   beer_servings                 193 non-null    int64
 2   spirit_servings               193 non-null    int64
 3   wine_servings                 193 non-null    int64
 4   total_litres_of_pure_alcohol  193 non-null    float64
 5   continent                     170 non-null    object
dtypes: float64(1), int64(3), object(2)
memory usage: 9.2+ KB

In [579]:
drinks['continent'].isna().sum()

23

## 4

In [580]:
medals[~medals['Country'].isin(drinks['country'])]

,Country,Code,SummerGame,SummerGold,SummerSilver,SummerBronze,WinterGame,WinterGold,WinterSilver,WinterBronze
4,Australasia,ANZ,2,3,4,5,0,0,0,0
13,Bermuda,BER,17,0,0,1,7,0,0,0
14,Bohemia,BOH,3,0,1,3,0,0,0,0
17,British West Indies,BWI,1,0,0,2,0,0,0,0
26,Ivory Coast,CIV,12,0,1,0,0,0,0,0
31,Czechoslovakia,TCH,16,49,49,45,16,2,8,15
45,United Team of Germany,EUA,3,28,54,36,3,8,6,5
46,East Germany,GDR,5,153,129,127,6,39,36,35
47,West Germany,FRG,5,56,67,81,6,11,15,13
49,Great Britain,GBR,27,236,272,272,22,10,4,12
55,Hong Kong,HKG,15,1,1,1,4,0,0,0
75,Liechtenstein,LIE,16,0,0,0,18,2,2,5
89,Netherlands Antilles,AHO,13,0,1,0,2,0,0,0
101,Puerto Rico,PUR,17,0,2,6,6,0,0,0
104,Russia,RUS,5,132,121,142,6,49,40,35
105,Russian Empire,RU1,3,1,4,3,0,0,0,0
106,Soviet Union,URS,9,395,319,296,9,78,57,59
107,Unified Team,EUN,1,45,38,29,1,9,6,8
111,Serbia and Montenegro,SCG,3,2,4,3,3,0,0,0
123,Chinese Taipei,TPE,13,2,7,12,11,0,0,0
129,Trinidad and Tobago,TRI,16,2,5,11,3,0,0,0
135,United States,USA,26,976,757,666,22,96,102,84
140,Virgin Islands,ISV,11,0,1,0,7,0,0,0
141,Yugoslavia,YUG,16,26,29,28,14,0,3,1
142,Independent Olympic Participants,IOP,1,0,1,2,0,0,0,0
145,Mixed team,ZZX,3,8,5,4,0,0,0,0

## 5

In [581]:
drinks[~drinks['country'].isin(medals['Country'])]

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
1,Albania,89,132,54,4.9,EU
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NaN
13,Bangladesh,0,0,0,0.0,AS
...,...,...,...,...,...,...
178,Tuvalu,6,41,9,1.0,OC
182,United Kingdom,219,126,195,10.4,EU
184,USA,249,158,84,8.7,NaN
187,Vanuatu,21,18,11,0.9,OC
190,Yemen,6,0,0,0.1,AS

## 6

In [582]:
medals.columns

Index(['Country', 'Code', 'SummerGame', 'SummerGold', 'SummerSilver',
       'SummerBronze', 'WinterGame', 'WinterGold', 'WinterSilver',
       'WinterBronze'],
      dtype='object')

In [583]:
# medals = medals.join(drinks['continent'])
medals = medals.merge(drinks[['continent']], left_index=True, right_index=True)
medals

,Country,Code,SummerGame,SummerGold,SummerSilver,SummerBronze,WinterGame,WinterGold,WinterSilver,WinterBronze,continent
0,Afghanistan,AFG,13,0,0,2,0,0,0,0,AS
1,Algeria,ALG,12,5,2,8,3,0,0,0,EU
2,Argentina,ARG,23,18,24,28,18,0,0,0,AF
3,Armenia,ARM,5,1,2,9,6,0,0,0,EU
4,Australasia,ANZ,2,3,4,5,0,0,0,0,AF
...,...,...,...,...,...,...,...,...,...,...,...
141,Yugoslavia,YUG,16,26,29,28,14,0,3,1,AS
142,Independent Olympic Participants,IOP,1,0,1,2,0,0,0,0,AF
143,Zambia,ZAM,12,0,1,1,0,0,0,0,NaN
144,Zimbabwe,ZIM,12,3,4,1,1,0,0,0,NaN
145,Mixed team,ZZX,3,8,5,4,0,0,0,0,NaN

## 7

In [584]:
medals[medals['continent'].isna()]
old_medals = medals

## 8

In [585]:
OC = ['Australasia']
NA = ['Canada', 'United States', 'Mexico']
SA = ['Cuba', 'Jamaica']
EU = ['Czech', 'Yugoslavia', 'Germany', 'Great Britain', 'Russia', 'Soviet']

In [586]:
medals.loc[medals.index.isin(OC), 'continent'] = 'OC'
medals.loc[medals.index.isin(NA), 'continent'] = 'NA'
medals.loc[medals.index.isin(SA), 'continent'] = 'SA'
medals.loc[medals.index.isin(EU), 'continent'] = 'EU'
# fill the rest NaN with 'OT'
medals['continent'].fillna('OT', inplace=True)

In [587]:
medals.isna().sum()

Country         0
Code            0
SummerGame      0
SummerGold      0
SummerSilver    0
SummerBronze    0
WinterGame      0
WinterGold      0
WinterSilver    0
WinterBronze    0
continent       0
dtype: int64

## 9

In [588]:
medals = medals.set_index(['continent', 'Country'])
medals.head()

,,Code,SummerGame,SummerGold,SummerSilver,SummerBronze,WinterGame,WinterGold,WinterSilver,WinterBronze
continent,Country,,,,,,,,,
AS,Afghanistan,AFG,13,0,0,2,0,0,0,0
EU,Algeria,ALG,12,5,2,8,3,0,0,0
AF,Argentina,ARG,23,18,24,28,18,0,0,0
EU,Armenia,ARM,5,1,2,9,6,0,0,0
AF,Australasia,ANZ,2,3,4,5,0,0,0,0

## 10

In [589]:
medals.sort_values(by=['continent', 'Country'])

                         Code  SummerGame  SummerGold  SummerSilver  \
continent Country
AF        Argentina       ARG          23          18            24
          Australasia     ANZ           2           3             4
          Bulgaria        BUL          19          51            85
          Chile           CHI          22           2             7
          Chinese Taipei  TPE          13           2             7
...                       ...         ...         ...           ...
SA        Eritrea         ERI           4           0             0
          Guatemala       GUA          13           0             1
          Kyrgyzstan      KGZ           5           0             1
          Uganda          UGA          14           2             3
          Ukraine         UKR           5          33            27

                          SummerBronze  WinterGame  WinterGold  WinterSilver  \
continent Country
AF        Argentina                 28          18           0             0
          Australasia                5           0           0             0
          Bulgaria                  78          19           1             2
          Chile                      4          16           0             0
          Chinese Taipei            12          11           0             0
...                                ...         ...         ...           ...
SA        Eritrea                    1           0           0             0
          Guatemala                  0           1           0             0
          Kyrgyzstan                 2           6           0             0
          Uganda                     2           0           0             0
          Ukraine                   55           6           2             1

                          WinterBronze
continent Country
AF        Argentina                  0
          Australasia                0
          Bulgaria                   3
          Chile                      0
          Chinese Taipei             0
...                                ...
SA        Eritrea                    0
          Guatemala                  0
          Kyrgyzstan                 0
          Uganda                     0
          Ukraine                    4

[146 rows x 9 columns]

## 11

In [590]:
medals.columns = pd.MultiIndex.from_tuples(
    [
        ('Code', 'Code'),
        ('Summer', 'Game'), 
        ('Summer', 'Gold'), 
        ('Summer', 'Silver'), 
        ('Summer', 'Bronze'),
        ('Winter', 'Game'), 
        ('Winter', 'Gold'), 
        ('Winter', 'Silver'), 
        ('Winter', 'Bronze'),
    ],
    names=['Season', 'Medal']
)
medals

Season                                     Code Summer                     \
Medal                                      Code   Game Gold Silver Bronze
continent Country
AS        Afghanistan                       AFG     13    0      0      2
EU        Algeria                           ALG     12    5      2      8
AF        Argentina                         ARG     23   18     24     28
EU        Armenia                           ARM      5    1      2      9
AF        Australasia                       ANZ      2    3      4      5
...                                         ...    ...  ...    ...    ...
AS        Yugoslavia                        YUG     16   26     29     28
AF        Independent Olympic Participants  IOP      1    0      1      2
OT        Zambia                            ZAM     12    0      1      1
          Zimbabwe                          ZIM     12    3      4      1
          Mixed team                        ZZX      3    8      5      4

Season                                     Winter
Medal                                        Game Gold Silver Bronze
continent Country
AS        Afghanistan                           0    0      0      0
EU        Algeria                               3    0      0      0
AF        Argentina                            18    0      0      0
EU        Armenia                               6    0      0      0
AF        Australasia                           0    0      0      0
...                                           ...  ...    ...    ...
AS        Yugoslavia                           14    0      3      1
AF        Independent Olympic Participants      0    0      0      0
OT        Zambia                                0    0      0      0
          Zimbabwe                              1    0      0      0
          Mixed team                            0    0      0      0

[146 rows x 9 columns]

## 12

In [591]:
medals = medals.swaplevel(axis=1)

## 13

In [592]:
long = medals.melt(ignore_index=False, value_name='Count').reset_index()
long.tail()

     continent                           Country   Medal  Season Count
1309        AS                        Yugoslavia  Bronze  Winter     1
1310        AF  Independent Olympic Participants  Bronze  Winter     0
1311        OT                            Zambia  Bronze  Winter     0
1312        OT                          Zimbabwe  Bronze  Winter     0
1313        OT                        Mixed team  Bronze  Winter     0

## 14

In [593]:
medals.groupby(level=['continent'])['Gold'].sum().iloc[:, :-1]

Medal       Gold
Season    Summer
continent
AF          1213
AS           430
EU          1822
OC           596
OT           490
SA           258

## 15

In [594]:
medals.groupby(level=0).size()

continent
AF    39
AS    31
EU    35
OC    11
OT    21
SA     9
dtype: int64

## 16

In [595]:
old_medals.groupby(by='continent')[['SummerGold', 'SummerSilver', 'SummerBronze']].sum()

           SummerGold  SummerSilver  SummerBronze
continent
AF               1213          1272          1394
AS                430           447           505
EU               1822          1730          1819
OC                596           524           533
OT                490           589           657
SA                258           213           222

## 17

In [596]:
res = medals.groupby(by='continent').sum()
pd.DataFrame(res[['Gold', 'Silver', 'Bronze']].sum())

                  0
Medal  Season
Gold   Summer  4809
       Winter   959
Silver Summer  4775
       Winter   958
Bronze Summer  5130
       Winter   948

## 18

In [597]:
old_medals.groupby(by='continent')['SummerGold'].mean()

continent
AF    31.102564
AS    13.870968
EU    52.057143
OC    54.181818
OT    23.333333
SA    28.666667
Name: SummerGold, dtype: float64

## 19

In [598]:
old_medals.groupby('continent')[['SummerGame', 'WinterGame']].count()

           SummerGame  WinterGame
continent
AF                 39          39
AS                 31          31
EU                 35          35
OC                 11          11
OT                 21          21
SA                  9           9

## 20

In [599]:
res = medals.groupby(by='continent').sum()
res.groupby('Medal', axis=1).sum()[['Gold', 'Silver', 'Bronze']]

Medal      Gold  Silver  Bronze
continent
AF         1378    1433    1558
AS          479     499     554
EU         2282    2171    2226
OC          766     683     697
OT          532     633     717
SA          331     314     326